# Generated by Django 6.0.2 on 2026-02-25 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_comment_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True, related_name="user_watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
