# Generated by Django 6.0.2 on 2026-02-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_text_comment_message_alter_listing_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="image_url",
        ),
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(default=1, upload_to="paintings/"),
            preserve_default=False,
        ),
    ]
